from ML_model.lstm import LSTM
from ML_model.resnet import resnet,ResNet
from ML_model.effnetv2 import effnetv2_s,EffNetV2
from ML_model.simple_vit import SimpleViT
from ML_model.vit import ViT
from ML_model.vit_2 import ViT2
from ML_model.simple_vit2 import SimpleViT2
from ML_model.kernel_transformer import Kernel_transformer
from ML_model.cosformer import Transformer_clf_model,cosformer
from ML_model.gru import myGRU,gru
from ML_model.preference import model_preference