from model.lstm import LSTM
from model.resnet import resnet,ResNet
from model.effnetv2 import effnetv2_s,EffNetV2
from model.simple_vit import SimpleViT
from model.vit import ViT
from model.vit_2 import ViT2
from model.simple_vit2 import SimpleViT2
from model.kernel_transformer import Kernel_transformer
from model.cosformer import Transformer_clf_model,cosformer
from model.gru import myGRU,gru