from models.lstm import LSTM
from models.resnet import resnet
from models.effnetv2 import effnetv2_s
from models.simple_vit import SimpleViT
from models.vit import ViT
from models.vit_2 import ViT2
from models.simple_vit2 import SimpleViT2
from models.kernel_transformer import Kernel_transformer
from models.cosformer import Transformer_clf_model
from models.gru import GRU